apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: "2022-10-20T23:58:20Z"
  name: example
spec:
  description: "Prints out a example manifest YAML for a given resource type. \nThe
    plugin works similar to a dry run output but for arbitrary resources.\nAll examples
    originate from kubernetes.io.\n"
  homepage: https://github.com/seredot/kubectl-example
  platforms:
  - bin: ./kubectl-example
    files:
    - from: kubectl-example
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        arch: arm64
        os: darwin
    sha256: 639a45faecc828ca29a71d85a7dcb85e89395f1c40651d449e78cfd4786077a7
    uri: https://github.com/seredot/kubectl-example/releases/download/v1.1.0/kubectl-example_1.1.0_Darwin_arm64.tar.gz
  - bin: ./kubectl-example
    files:
    - from: kubectl-example
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: darwin
    sha256: eaab1517d6a4f9064584b31fdd013883922cd0a86b3e8dbdf745132aa9090671
    uri: https://github.com/seredot/kubectl-example/releases/download/v1.1.0/kubectl-example_1.1.0_Darwin_x86_64.tar.gz
  - bin: ./kubectl-example
    files:
    - from: kubectl-example
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        arch: arm
        os: linux
    sha256: 4040b9ff76958e8b7ebfd1a94fe73ac4031a4e1567105374d2cab2f318ea8993
    uri: https://github.com/seredot/kubectl-example/releases/download/v1.1.0/kubectl-example_1.1.0_Linux_armv6.tar.gz
  - bin: ./kubectl-example
    files:
    - from: kubectl-example
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        arch: arm64
        os: linux
    sha256: e4d18043e0dfac74c175eb8eacfba91e37a510293ffe56af1041c0f5cc192d3e
    uri: https://github.com/seredot/kubectl-example/releases/download/v1.1.0/kubectl-example_1.1.0_Linux_arm64.tar.gz
  - bin: ./kubectl-example
    files:
    - from: kubectl-example
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: linux
    sha256: c5ef88e5046d3a813f838c1aa20f5412ef25694d26d950f403cac4b9a80df6cb
    uri: https://github.com/seredot/kubectl-example/releases/download/v1.1.0/kubectl-example_1.1.0_Linux_x86_64.tar.gz
  - bin: ./kubectl-example.exe
    files:
    - from: kubectl-example.exe
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        arch: arm64
        os: windows
    sha256: b716ef9bf424bbe9964b3f17836196cca37a22e152156939a729911712c03675
    uri: https://github.com/seredot/kubectl-example/releases/download/v1.1.0/kubectl-example_1.1.0_Windows_arm64.tar.gz
  - bin: ./kubectl-example.exe
    files:
    - from: kubectl-example.exe
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: windows
    sha256: cad6c00a402be39eaea4e6796ab381481e25f5b7631c1e2810df4eaeacab70f7
    uri: https://github.com/seredot/kubectl-example/releases/download/v1.1.0/kubectl-example_1.1.0_Windows_x86_64.tar.gz
  shortDescription: Prints out example manifest YAMLs
  version: v1.1.0
status:
  source:
    name: default
