apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: "2022-10-20T23:58:36Z"
  name: explore
spec:
  description: |
    Fuzzy-find and explain the fields associated with
    supported API resource.
  homepage: https://github.com/keisku/kubectl-explore
  platforms:
  - bin: kubectl-explore
    files: null
    selector:
      matchLabels:
        arch: amd64
        os: darwin
    sha256: 58f26e6814029887783535da1fcffff751ff520c2d32517e92802ee5d0873b69
    uri: https://github.com/keisku/kubectl-explore/releases/download/v0.7.0/kubectl-explore_v0.7.0_darwin_amd64.tar.gz
  - bin: kubectl-explore
    files: null
    selector:
      matchLabels:
        arch: arm64
        os: darwin
    sha256: 65ce4437c06467962ae22c694331dfecb29c99ddb981361c3f3f390d0dee596b
    uri: https://github.com/keisku/kubectl-explore/releases/download/v0.7.0/kubectl-explore_v0.7.0_darwin_arm64.tar.gz
  - bin: kubectl-explore
    files: null
    selector:
      matchLabels:
        arch: amd64
        os: linux
    sha256: dd211ad4e6d0b11d8e976660329e39f3ba0e0f3f642b83f65d8b77a73d584ff2
    uri: https://github.com/keisku/kubectl-explore/releases/download/v0.7.0/kubectl-explore_v0.7.0_linux_amd64.tar.gz
  - bin: kubectl-explore
    files: null
    selector:
      matchLabels:
        arch: arm64
        os: linux
    sha256: 9eda4efe6bda91293639763af797a23a6d8cb437460d04f4fee9d4f62fd2ae81
    uri: https://github.com/keisku/kubectl-explore/releases/download/v0.7.0/kubectl-explore_v0.7.0_linux_arm64.tar.gz
  - bin: kubectl-explore.exe
    files: null
    selector:
      matchLabels:
        arch: amd64
        os: windows
    sha256: 89d4a9cbf7c217e633b4f4c7c44b529be6f99c34d155456c3cede95406266071
    uri: https://github.com/keisku/kubectl-explore/releases/download/v0.7.0/kubectl-explore_v0.7.0_windows_amd64.tar.gz
  shortDescription: A better kubectl explain with the fuzzy finder
  version: v0.7.0
status:
  source:
    name: default
