apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: "2022-10-21T00:04:11Z"
  name: topology
spec:
  description: |
    Provides insight into the topology of a Kubernetes cluster (i.e. into the
    distribution of nodes and pods per region and zone).

    NOTE: Requires nodes to be adequately labeled with the
    'topology.kubernetes.io/{region,zone}' labels or their deprecated
    equivalents, 'failure-domain.beta.kubernetes.io/{region,zone}'.

    # List all pods across all namespaces and the zones and regions they are in.
    $ kubectl-topology pod --all-namespaces
    NAMESPACE     NAME                                     NODE                          REGION         ZONE
    kube-system   kube-dns-5f886bf8d8-s7pcc                gke-gke-1-p-1-50120dfc-26gm   europe-west1   europe-west1-d
    kube-system   kube-dns-5f886bf8d8-zhm42                gke-gke-1-p-1-8e1077f6-17st   europe-west1   europe-west1-b
    kube-system   kube-dns-autoscaler-8687c64fc-d5jvm      gke-gke-1-p-1-8e1077f6-17st   europe-west1   europe-west1-b
    kube-system   kube-proxy-gke-gke-1-p-1-50120dfc-26gm   gke-gke-1-p-1-50120dfc-26gm   europe-west1   europe-west1-d
    kube-system   kube-proxy-gke-gke-1-p-1-7023cbca-cz4b   gke-gke-1-p-1-7023cbca-cz4b   europe-west1   europe-west1-c
    kube-system   kube-proxy-gke-gke-1-p-1-8e1077f6-17st   gke-gke-1-p-1-8e1077f6-17st   europe-west1   europe-west1-b
    kube-system   l7-default-backend-8f479dd9-dkspg        gke-gke-1-p-1-50120dfc-26gm   europe-west1   europe-west1-d
    kube-system   metrics-server-v0.3.1-5c6fbf777-z7jxq    gke-gke-1-p-1-8e1077f6-17st   europe-west1   europe-west1-b
    ns-1          nginx                                    gke-gke-1-p-1-7023cbca-cz4b   europe-west1   europe-west1-c
  homepage: https://github.com/bmcustodio/kubectl-topology
  platforms:
  - bin: kubectl-topology
    files:
    - from: kubectl-topology
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: darwin
    sha256: a8c9740329481dcff64a93697820bdef375d4fbc30cfe8df2869df948e923f0d
    uri: https://github.com/bmcustodio/kubectl-topology/releases/download/v0.1.1/kubectl-topology_v0.1.1_darwin_amd64.tar.gz
  - bin: kubectl-topology
    files:
    - from: kubectl-topology
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: linux
    sha256: 3aa1ecd9ab4c13e9f1bc88f1a171bd28835863c4abfd038756e5ca39bd6929af
    uri: https://github.com/bmcustodio/kubectl-topology/releases/download/v0.1.1/kubectl-topology_v0.1.1_linux_amd64.tar.gz
  - bin: kubectl-topology.exe
    files:
    - from: kubectl-topology.exe
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: windows
    sha256: 545dbc904ef25388621ca12b080aa174fd6c724f62443490aa30515152dcd4ab
    uri: https://github.com/bmcustodio/kubectl-topology/releases/download/v0.1.1/kubectl-topology_v0.1.1_windows_amd64.tar.gz
  shortDescription: Explore region topology for nodes or pods
  version: v0.1.1
status:
  source:
    name: default
